# Generated by Django 3.1.4 on 2021-03-01 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('start_date', models.DateField()),
                ('office_number', models.CharField(blank=True, max_length=10)),
                ('office_phone_number', models.CharField(blank=True, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('year', models.CharField(choices=[('10', '10th Grade'), ('11', '11th Grade'), ('12', '12th Grade')], max_length=2)),
                ('student_id_no', models.PositiveIntegerField(unique=True)),
            ],
        ),
    ]
