# Generated by Django 3.1.4 on 2021-03-03 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_extracurricular'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtraCurricular',
        ),
    ]
