# Generated by Django 3.1.4 on 2021-03-03 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_extracurricular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='office_phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
