# Generated by Django 3.1.4 on 2021-03-02 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20210302_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='lecture_title',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(max_length=150),
        ),
    ]
