# Generated by Django 3.1.4 on 2021-03-03 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='content',
            field=models.FileField(null=True, upload_to='file_uploads'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='content',
            field=models.FileField(null=True, upload_to='file_uploads'),
        ),
    ]
