# Generated by Django 3.1.4 on 2021-03-03 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_extracurricular'),
        ('school', '0008_extracurricular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extracurricular',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student'),
        ),
    ]
